import { z } from "zod";

const schema = z.object({
  DATABASE_URL: z.string().min(1),
  SESSION_SECRET: z.string().min(8),
  APP_URL: z.string().default("http://localhost:3000"),
  INTEGRATION_API_KEY: z.string().default(""),
  CRAD_STUDENT_LIST_ENDPOINT: z.string().default(""),
  PREFECT_STUDENT_PERSONAL_INFO_ENDPOINT: z.string().default(""),
  COMLAB_STUDENT_LIST_ENDPOINT: z.string().default(""),
  CASHIER_ENROLLMENT_DATA_ENDPOINT: z.string().default(""),
  CLINIC_STUDENT_PERSONAL_INFO_ENDPOINT: z.string().default(""),
  GUIDANCE_STUDENT_PERSONAL_INFO_ENDPOINT: z.string().default(""),
  GUIDANCE_STUDENT_ACADEMIC_RECORDS_ENDPOINT: z.string().default(""),
  PMED_ENROLLMENT_STATISTICS_ENDPOINT: z.string().default(""),
  PMED_REPORT_QUEUE_ENDPOINT: z.string().default("")
});

export const env = schema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  SESSION_SECRET: process.env.SESSION_SECRET ?? "change-me-now",
  APP_URL: process.env.APP_URL,
  INTEGRATION_API_KEY: process.env.INTEGRATION_API_KEY ?? "",
  CRAD_STUDENT_LIST_ENDPOINT: process.env.CRAD_STUDENT_LIST_ENDPOINT ?? "",
  PREFECT_STUDENT_PERSONAL_INFO_ENDPOINT: process.env.PREFECT_STUDENT_PERSONAL_INFO_ENDPOINT ?? "",
  COMLAB_STUDENT_LIST_ENDPOINT: process.env.COMLAB_STUDENT_LIST_ENDPOINT ?? "",
  CASHIER_ENROLLMENT_DATA_ENDPOINT: process.env.CASHIER_ENROLLMENT_DATA_ENDPOINT ?? "",
  CLINIC_STUDENT_PERSONAL_INFO_ENDPOINT: process.env.CLINIC_STUDENT_PERSONAL_INFO_ENDPOINT ?? "",
  GUIDANCE_STUDENT_PERSONAL_INFO_ENDPOINT: process.env.GUIDANCE_STUDENT_PERSONAL_INFO_ENDPOINT ?? "",
  GUIDANCE_STUDENT_ACADEMIC_RECORDS_ENDPOINT: process.env.GUIDANCE_STUDENT_ACADEMIC_RECORDS_ENDPOINT ?? "",
  PMED_ENROLLMENT_STATISTICS_ENDPOINT: process.env.PMED_ENROLLMENT_STATISTICS_ENDPOINT ?? "",
  PMED_REPORT_QUEUE_ENDPOINT: process.env.PMED_REPORT_QUEUE_ENDPOINT ?? ""
});
